In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("employee_data.csv")

print(df)

      id groups  age  healthy_eating  active_lifestyle  salary
0      0      A   36               5                 5    2297
1      1      A   55               3                 5    1134
2      2      A   61               8                 1    4969
3      3      O   29               3                 6     902
4      4      O   34               6                 2    3574
5      5      O   42               5                 3    2761
6      6     AB   53               4                 6    1484
7      7      B   41               8                 6    3809
8      8      A   47               5                 6    2065
9      9      A   31               4                 8    1020
10    10      A   47               6                 9    1950
11    11      O   40               7                 1    4387
12    12      O   41               3                 2    1830
13    13      O   46               6                 8    2182
14    14     AB   51               7                 5 

In [2]:
df1=df[0:200].copy()
del df1['id']
del df1['groups']

In [3]:
from sklearn.cluster import KMeans
di=0.0
di1=0.0

for i in range(2,21):
    kmeans = KMeans(n_clusters=i,random_state=1)
    kmeans.fit(df1[0:180])
    labels=kmeans.labels_  
    labels=list(labels)
    centroids=kmeans.cluster_centers_
    #print(centroids)
    min_=centroids[1]-centroids[0]
    min_squared=min_[0]**2+min_[1]**2+min_[2]**2
    min_squared=min_squared**.5
    #dunn's Index
    for j in range(len(centroids)):
        #calculating Minimum distance between clusters
        for k in range(j+1,len(centroids)):
            dist=centroids[k]-centroids[j]
            dist_squared=dist[0]**2+dist[1]**2+dist[2]**2
            dist_squared=dist_squared**.5
            if(dist_squared<min_squared):
                min_squared=dist_squared
    print(i)
    sum_=[]
    for j in range(len(centroids)):
        sum_.append(0)
    for j in range(len(labels)):
        #Calculating Delta
        for k in range(j+1,len(labels)):
            if(labels[j]==labels[k]):
                dist1=(df1.iloc[j]['age']-df1.iloc[k]['age'])**2+(df1.iloc[j]['healthy_eating']-df.iloc[k]['healthy_eating'])**2+(df1.iloc[j]['active_lifestyle']-df1.iloc[k]['active_lifestyle'])**2+(df1.iloc[j]['age']-df1.iloc[k]['age'])**2
            
                dist1_squared=dist1**.5
               
                sum_[labels[j]]=sum_[labels[j]]+dist1_squared
                
    for j in range(len(centroids)):
        cn=labels.count(j)
        if(cn==1):
            sum_[j]=0;
        else:
            sum_[j]=(sum_[j])/(cn) # cannot allow (cn-1) as division by zero may occur
            
    
    di=min_squared/max(sum_)
    print(di)

    if (di>di1):
        di1=di
        final_n=i
print("Optimal Number of Clusters = ",final_n)
   
kmeans = KMeans(n_clusters=final_n,random_state=1)
kmeans.fit(df1[0:180])
cluster_labels_train=kmeans.labels_

2
0.0035388143869980676
3
0.003568882106809988
4
0.0035933456506561804
5
0.004445711783335497
6
0.004948053271207157
7
0.0021265190576738842
8
0.002669360129629281
9
0.005353521118876674
10
0.0036688904973772715
11
0.0034967988853607268
12
0.0035231986555647487
13
0.003502163236165694
14
0.003502163236165694
15
0.0019481797224307183
16
0.0023994128014054052
17
0.0023994128014054052
18
0.0026162373217625636
19
0.0026942311037361838
20
0.0022271318630732455
Optimal Number of Clusters =  9


In [4]:
train_df=df[0:180].copy()
train_df['Labels']=cluster_labels_train
train_df

id groups  age  healthy_eating  active_lifestyle  salary  Labels
0      0      A   36               5                 5    2297       4
1      1      A   55               3                 5    1134       7
2      2      A   61               8                 1    4969       2
3      3      O   29               3                 6     902       3
4      4      O   34               6                 2    3574       5
5      5      O   42               5                 3    2761       0
6      6     AB   53               4                 6    1484       1
7      7      B   41               8                 6    3809       5
8      8      A   47               5                 6    2065       4
9      9      A   31               4                 8    1020       7
10    10      A   47               6                 9    1950       8
11    11      O   40               7                 1    4387       2
12    12      O   41               3                 2    1830       8
13    13      O   46               6                 8    2182       4
14    14     AB   51               7                 5    3460       6
15    15      B   57               3                 8     662       3
16    16      A   33               3                 5    1134       7
17    17      A   41               4                 8    1020       7
18    18      A   46               2                 6     779       3
19    19      O   32               7                 6    3228       6
20    20      O   57               7                 6    3228       6
21    21      O   26               1                 6    1360       1
22    22     AB   59               7                 5    3460       6
23    23      B   55               6                 4    3110       6
24    24      A   51               5                 8    1601       1
25    25      A   63               6                 7    2414       4
26    26      A   62               9                 6    4390       2
27    27      O   37               3                 5    1134       7
28    28      O   63               6                 7    2414       4
29    29      O   20               8                 6    3809       5
..   ...    ...  ...             ...               ...     ...     ...
150  150     AB   49               5                 4    2529       0
151  151      B   58               1                 6    1360       1
152  152      A   55               7                 3    3923       5
153  153      A   54               6                 5    2878       0
154  154      A   51               4                 7    1252       7
155  155      O   34               6                 9    1950       8
156  156      O   19               5                 6    2065       4
157  157      O   51               7                 5    3460       6
158  158     AB   44               6                 9    1950       8
159  159      B   30               7                 6    3228       6
160  160      A   32               4                 5    1716       8
161  161      A   52               2                 6     779       3
162  162      A   33               7                 6    3228       6
163  163      O   25               7                 6    3228       6
164  164      O   36               3                 9     894       3
165  165      O   27               7                 3    3923       5
166  166     AB   59               6                 8    2182       4
167  167      B   38               3                 8     662       3
168  168      A   54               8                 5    4041       5
169  169      A   58               5                 5    2297       4
170  170      A   63               5                 2    2993       6
171  171      O   50               3                 6     902       3
172  172      O   32               2                 6     779       3
173  173      O   58               9                 5    4622       2
174  174     AB   21          

In [5]:
centroids=kmeans.cluster_centers_
centroids_no_salary=[]
d=[]
for i in range(len(centroids)):
    d=centroids[i]
    centroids_no_salary.append((d[:3]))
print(centroids_no_salary)

[array([41.32,  5.8 ,  5.12]), array([37.  ,  3.45,  6.05]), array([44.6,  8.4,  3.5]), array([45.53846154,  2.76923077,  6.69230769]), array([46.7       ,  5.2       ,  6.66666667]), array([38.07692308,  7.38461538,  4.15384615]), array([39.39130435,  6.52173913,  4.86956522]), array([41.5625,  3.1875,  6.125 ]), array([43.58823529,  4.70588235,  6.17647059])]


In [7]:
test_df=df[180:200].copy()
cluster_labels_test=[]
features=[]

for i in range(20):
    tmp=[]
    for j in range(2,5):
        tmp.append(float(test_df.iloc[i,j]))
    features.append(tmp)
features=np.array(features)
print(features)

[[35.  3.  6.]
 [30.  7.  8.]
 [49.  8.  5.]
 [61.  4.  7.]
 [31.  5.  6.]
 [38.  8.  5.]
 [22.  5.  5.]
 [23.  3.  8.]
 [48.  8.  6.]
 [34.  4.  6.]
 [33.  6.  8.]
 [43.  7.  5.]
 [43.  3.  6.]
 [36.  4.  5.]
 [34.  4.  5.]
 [56.  5.  7.]
 [18.  3.  4.]
 [51.  8.  6.]
 [34.  3.  6.]
 [50.  4.  3.]]


In [8]:
labels=[]
for i in range(20):
    min_diff_list=centroids_no_salary[0]-features[i]
    min_diff_squared=(min_diff_list[0]**2+min_diff_list[1]**2+min_diff_list[2]**2)**.5
    index=0;
    for j in range(1,len(centroids)):
        diff_list=centroids_no_salary[j]-features[i]
        diff_squared=(diff_list[0]**2+diff_list[1]**2+diff_list[2]**2)**.5
        if(diff_squared<min_diff_squared):
            min_diff_sqaured=diff_squared
            index=j
    labels.append(index)
            
test_df['Labels']=labels
test_df

id groups  age  healthy_eating  active_lifestyle  salary  Labels
180  180      O   35               3                 6     902       7
181  181      O   30               7                 8    2764       6
182  182     AB   49               8                 5    4041       8
183  183      B   61               4                 7    1252       8
184  184      A   31               5                 6    2065       6
185  185      A   38               8                 5    4041       6
186  186      A   22               5                 5    2297       6
187  187      O   23               3                 8     662       7
188  188      O   48               8                 6    3809       8
189  189      O   34               4                 6    1484       6
190  190     AB   33               6                 8    2182       6
191  191      B   43               7                 5    3460       0
192  192      A   43               3                 6     902       8
193  193      A   36               4                 5    1716       6
194  194      A   34               4                 5    1716       6
195  195      O   56               5                 7    1833       8
196  196      O   18               3                 4    1366       6
197  197      O   51               8                 6    3809       8
198  198     AB   34               3                 6     902       7
199  199      B   50               4                 3    2179       8

In [49]:
min_label = test_df['Labels'].min()
max_label = test_df['Labels'].max()

print(min_label)
print(max_label)

cust_seg = pd.DataFrame(columns=['label', 'min_sal', 'max_sal','min_age','max_age'])

for i in range(min_label,max_label+1):
    rslt_df = test_df.loc[test_df['Labels'] == i]
    max_sal = rslt_df['salary'].max()
    min_sal = rslt_df['salary'].min()
    max_age = rslt_df['age'].max()
    min_age = rslt_df['age'].min()
    print(i,max_sal , min_sal, max_age , min_age)

0
8
0 3460 3460 43 43
1 nan nan nan nan
2 nan nan nan nan
3 nan nan nan nan
4 nan nan nan nan
5 nan nan nan nan
6 4041 1366 38 18
7 902 662 35 23
8 4041 902 61 43
