In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 1000)
df=pd.read_csv("employee_data.csv")

print(df)

      id groups  age  healthy_eating  active_lifestyle  salary
0      0      A   36               5                 5    2297
1      1      A   55               3                 5    1134
2      2      A   61               8                 1    4969
3      3      O   29               3                 6     902
4      4      O   34               6                 2    3574
5      5      O   42               5                 3    2761
6      6     AB   53               4                 6    1484
7      7      B   41               8                 6    3809
8      8      A   47               5                 6    2065
9      9      A   31               4                 8    1020
10    10      A   47               6                 9    1950
11    11      O   40               7                 1    4387
12    12      O   41               3                 2    1830
13    13      O   46               6                 8    2182
14    14     AB   51               7                 5 

In [2]:
df1=df[0:200].copy()
del df1['id']
del df1['groups']
#including salary too: Reason : Kmeans predictions requires all the features and its is needed for better clustering.
#clustering has been done using all the relevant features inlcuding salary for better clustering.


In [3]:

from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
scaled_df1 = scaler.fit_transform(df1)
scaled_df1 = pd.DataFrame(scaled_df1, columns=['age', 'healthy_eating', 'active_lifestyle','salary'])
scaled_df1

age  healthy_eating  active_lifestyle    salary
0   -0.447355       -0.013078         -0.357260  0.048003
1    0.993280       -1.059299         -0.357260 -1.020373
2    1.448217        1.556254         -2.342035  2.502604
3   -0.978115       -1.059299          0.138934 -1.233497
4   -0.599001        0.510033         -1.845841  1.221104
5    0.007582       -0.013078         -1.349647  0.474252
6    0.841634       -0.536188          0.138934 -0.698849
7   -0.068241        1.556254          0.138934  1.436984
8    0.386697       -0.013078          0.138934 -0.165121
9   -0.826469       -0.536188          1.131322 -1.125097
10   0.386697        0.510033          1.627516 -0.270764
11  -0.144063        1.033143         -2.342035  1.967957
12  -0.068241       -1.059299         -1.845841 -0.381001
13   0.310874        0.510033          1.131322 -0.057640
14   0.689988        1.033143         -0.357260  1.116380
15   1.144925       -1.059299          1.131322 -1.453970
16  -0.674824       -1.059299         -0.357260 -1.020373
17  -0.068241       -0.536188          1.131322 -1.125097
18   0.310874       -1.582409          0.138934 -1.346489
19  -0.750646        1.033143          0.138934  0.903256
20   1.144925        1.033143          0.138934  0.903256
21  -1.205584       -2.105520          0.138934 -0.812760
22   1.296571        1.033143         -0.357260  1.116380
23   0.993280        0.510033         -0.853454  0.794856
24   0.689988       -0.013078          1.131322 -0.591369
25   1.599863        0.510033          0.635128  0.155484
26   1.524040        2.079364          0.138934  1.970713
27  -0.371532       -1.059299         -0.357260 -1.020373
28   1.599863        0.510033          0.635128  0.155484
29  -1.660521        1.556254          0.138934  1.436984
30   1.599863       -0.536188          0.635128 -0.911973
31   0.917457        1.033143          1.131322  0.477007
32   1.220748       -1.059299          1.131322 -1.453970
33  -1.812167       -0.536188          0.138934 -0.698849
34  -0.978115       -0.013078          0.635128 -0.378245
35   1.448217       -1.582409         -0.853454 -1.340977
36   0.689988       -0.013078         -0.357260  0.048003
37  -1.508875       -1.059299         -0.357260 -1.020373
38  -0.447355       -1.059299          0.635128 -1.446621
39   1.524040       -1.582409          0.138934 -1.346489
40   0.917457        0.510033          1.131322 -0.057640
41   0.993280       -0.013078         -1.349647  0.474252
42   0.993280        0.510033          0.635128  0.155484
43   0.007582       -0.536188          2.123710 -1.551346
44  -0.068241        0.510033          0.138934  0.368608
45   0.083405       -0.013078          1.131322 -0.591369
46  -1.357230       -0.536188         -1.349647 -0.060396
47   0.159228       -0.536188          0.138934 -0.698849
48   0.007582       -0.013078          0.138934 -0.165121
49   0.917457        0.510033          1.627516 -0.270764
50  -0.599001       -1.059299          0.138934 -1.233497
51  -0.750646       -0.013078          1.131322 -0.591369
52  -1.053938        1.033143         -1.845841  1.754833
53  -1.812167       -1.582409         -0.853454 -1.340977
54   1.675686       -1.059299          0.635128 -1.446621
55   0.159228        0.510033         -0.357260  0.581732
56   1.069103       -0.013078         -0.357260  0.048003
57   0.917457        0.510033         -2.342035  1.434228
58  -1.433052        2.079364          0.138934  1.970713
59   0.007582        1.556254         -1.349647  2.076356
60   1.675686        1.033143          2.123710  0.050759
61   1.144925       -1.059299         -0.357260 -1.020373
62  -1.660521       -0.013078         -0.357260  0.048003
63  -0.371532       -0.013078         -1.349647  0.474252
64   0.235051        1.033143         -0.853454  1.328585
65   0.235051        0.510033          0.138934  0.368608
66  -1.129761       -1.059299         -0.853454 -0.807249
67   0.083405        0.510033         -1.349647  1.007980
68  -1.6

In [4]:
from sklearn.cluster import KMeans
di=0.0
di1=0.0

for i in range(2,21):
    kmeans = KMeans(n_clusters=i,random_state=1)
    kmeans.fit(scaled_df1[0:180])
    labels=kmeans.labels_  
    labels=list(labels)
    centroids=kmeans.cluster_centers_
    #print(centroids)
    min_=centroids[1]-centroids[0]
    min_squared=min_[0]**2+min_[1]**2+min_[2]**2
    min_squared=min_squared**.5
    #dunn's Index
    for j in range(len(centroids)):
        #calculating Minimum distance between clusters
        for k in range(j+1,len(centroids)):
            dist=centroids[k]-centroids[j]
            dist_squared=dist[0]**2+dist[1]**2+dist[2]**2
            dist_squared=dist_squared**.5
            if(dist_squared<min_squared):
                min_squared=dist_squared
    print(i)
    sum_=[]
    for j in range(len(centroids)):
        sum_.append(0)
    for j in range(len(labels)):
        #Calculating Delta
        for k in range(j+1,len(labels)):
            if(labels[j]==labels[k]):
                dist1=(scaled_df1.iloc[j]['age']-scaled_df1.iloc[k]['age'])**2+(scaled_df1.iloc[j]['healthy_eating']-scaled_df1.iloc[k]['healthy_eating'])**2+(scaled_df1.iloc[j]['active_lifestyle']-scaled_df1.iloc[k]['active_lifestyle'])**2+(scaled_df1.iloc[j]['salary']-scaled_df1.iloc[k]['salary'])**2
            
                dist1_squared=dist1**.5
               
                sum_[labels[j]]=sum_[labels[j]]+dist1_squared
                
    for j in range(len(centroids)):
        cn=labels.count(j)
        if(cn==1):
            sum_[j]=0;
        else:
            sum_[j]=(sum_[j])/(cn) # cannot allow (cn-1) as division by zero may occur
            
    
    di=min_squared/max(sum_)
    print(di)

    if (di>di1):
        di1=di
        final_n=i
print("Optimal Number of Clusters = ",final_n)
   
kmeans = KMeans(n_clusters=final_n,random_state=1)
kmeans.fit(scaled_df1[0:180])
cluster_labels_train=kmeans.labels_



2
0.015052324845163648
3
0.026927292951708544
4
0.03000754023261809
5
0.04838479256480625
6
0.059683074994509394
7
0.06640083363309812
8
0.05613955706273812
9
0.08332432697879932
10
0.06881701707140879
11
0.07727913247482819
12
0.07155503765202624
13
0.0766140886299399
14
0.10509861321355689
15
0.09647835588766336
16
0.11459974905392083
17
0.10341622045244582
18
0.0855997693161557
19
0.1375497678809205
20
0.10612981397210548
Optimal Number of Clusters =  19


In [5]:
#adding the cluster no. to train dataframe
train_df=df[0:180].copy()
train_df['Labels']=cluster_labels_train
train_df


id groups  age  healthy_eating  active_lifestyle  salary  Labels
0      0      A   36               5                 5    2297       3
1      1      A   55               3                 5    1134       2
2      2      A   61               8                 1    4969      13
3      3      O   29               3                 6     902       4
4      4      O   34               6                 2    3574       1
5      5      O   42               5                 3    2761      16
6      6     AB   53               4                 6    1484       2
7      7      B   41               8                 6    3809      15
8      8      A   47               5                 6    2065       3
9      9      A   31               4                 8    1020       0
10    10      A   47               6                 9    1950       6
11    11      O   40               7                 1    4387      18
12    12      O   41               3                 2    1830       9
13    13      O   46               6                 8    2182       6
14    14     AB   51               7                 5    3460       5
15    15      B   57               3                 8     662      10
16    16      A   33               3                 5    1134      14
17    17      A   41               4                 8    1020       0
18    18      A   46               2                 6     779       2
19    19      O   32               7                 6    3228       8
20    20      O   57               7                 6    3228       5
21    21      O   26               1                 6    1360       4
22    22     AB   59               7                 5    3460       5
23    23      B   55               6                 4    3110       5
24    24      A   51               5                 8    1601       6
25    25      A   63               6                 7    2414      12
26    26      A   62               9                 6    4390      15
27    27      O   37               3                 5    1134      14
28    28      O   63               6                 7    2414      12
29    29      O   20               8                 6    3809       8
30    30     AB   63               4                 7    1252      10
31    31      B   54               7                 8    2764       6
32    32      A   58               3                 8     662      10
33    33      A   18               4                 6    1484       4
34    34      A   29               5                 7    1833      11
35    35      O   61               2                 4     785       2
36    36      O   51               5                 5    2297       3
37    37      O   22               3                 5    1134       4
38    38     AB   36               3                 7     670      14
39    39      B   62               2                 6     779       2
40    40      A   54               6                 8    2182       6
41    41      A   55               5                 3    2761      16
42    42      A   55               6                 7    2414      12
43    43      O   42               4                10     556       0
44    44      O   41               6                 6    2646       3
45    45      O   43               5                 8    1601       6
46    46     AB   24               4                 3    2179      17
47    47      B   44               4                 6    1484      14
48    48      A   42               5                 6    2065       3
49    49      A   54               6                 9    1950       6
50    50      A   34               3                 6     902      14
51    51      O   32               5                 8    1601      11
52    52      O   28               7                 2    4155       1
53    53      O   18               2                 4     785      17
54    54     AB   64               3                 7     670      10
55    55      B   44          

In [6]:
#Setting the cluster no. for test data based on Centroid Distance from test data
centroids=kmeans.cluster_centers_

print(centroids)                               
        

[[-0.17163542 -1.05929878  1.44708186 -1.08116984]
 [-1.18392009  0.3605726  -1.84584132  1.06861039]
 [ 1.04577247 -1.38121294 -0.28092209 -1.08828126]
 [ 0.21338724  0.21111246 -0.14460508  0.18540545]
 [-1.29519262 -0.96418778  0.22915137 -1.00124833]
 [ 0.91204091  0.84631807 -0.42814445  0.95568352]
 [ 0.58889102  0.57978081  1.39595885 -0.0998973 ]
 [-1.3151057   0.33566258 -0.2469943   0.3564617 ]
 [-1.11712374  1.25110597  0.18028379  1.10788217]
 [-0.05740875 -0.98456871 -1.42053226 -0.48730012]
 [ 1.23591292 -1.11160983  0.93284454 -1.16193484]
 [-1.01061065  0.28584253  0.98955242 -0.22548826]
 [ 1.28393407  0.37925512  0.71782718 -0.01346877]
 [ 1.44821698  1.55625376 -2.34203523  2.5026045 ]
 [-0.32328118 -0.82152128  0.00360868 -0.93235047]
 [ 0.60333348  1.92990413 -0.00283539  1.87911168]
 [ 0.3108738   0.04504563 -1.34964742  0.53345265]
 [-1.53920443 -1.16392088 -1.15116986 -0.78611998]
 [-0.15922804  1.24238746 -2.14355767  2.09675018]]


In [7]:
scaled_test_df=scaled_df1[180:200].copy()
cluster_labels_test=[]
features=[]
#getting the relevant features from the test data and storing them in a list for comparison with centroids.
for i in range(20):
    tmp=[]
    for j in range(0,4):
        tmp.append(float(scaled_test_df.iloc[i,j]))
    features.append(tmp)
features=np.array(features)
print(features)

[[-0.52317786 -1.05929878  0.13893429 -1.23349675]
 [-0.90229225  1.03314325  1.1313221   0.47700744]
 [ 0.53834244  1.55625376 -0.35725961  1.65010832]
 [ 1.44821698 -0.53618827  0.6351282  -0.9119734 ]
 [-0.82646937 -0.01307776  0.13893429 -0.16512061]
 [-0.29570923  1.55625376 -0.35725961  1.65010832]
 [-1.50887528 -0.01307776 -0.35725961  0.04800344]
 [-1.4330524  -1.05929878  1.1313221  -1.45396989]
 [ 0.46251956  1.55625376  0.13893429  1.43698428]
 [-0.59900074 -0.53618827  0.13893429 -0.69884936]
 [-0.67482362  0.51003275  1.1313221  -0.05763995]
 [ 0.08340517  1.03314325 -0.35725961  1.11637957]
 [ 0.08340517 -1.05929878  0.13893429 -1.23349675]
 [-0.44735498 -0.53618827 -0.35725961 -0.48572531]
 [-0.59900074 -0.53618827 -0.35725961 -0.48572531]
 [ 1.06910259 -0.01307776  0.6351282  -0.37824465]
 [-1.81216679 -1.05929878 -0.85345352 -0.80724866]
 [ 0.68998819  1.55625376  0.13893429  1.43698428]
 [-0.59900074 -1.05929878  0.13893429 -1.23349675]
 [ 0.61416532 -0.53618827 -1.34

In [8]:
#deciding the cluster no. for test data
test_df=df[180:200].copy()
labels=[]
for i in range(20):
    min_diff_list=centroids[0]-features[i]
    min_diff_squared=(min_diff_list[0]**2+min_diff_list[1]**2+min_diff_list[2]**2)**.5
    index=0;
    for j in range(1,len(centroids)):
        diff_list=centroids[j]-features[i]
        diff_squared=(diff_list[0]**2+diff_list[1]**2+diff_list[2]**2)**.5
        if(diff_squared<min_diff_squared):
            min_diff_sqaured=diff_squared
            index=j
    labels.append(index)
            
test_df['Labels']=labels
test_df

id groups  age  healthy_eating  active_lifestyle  salary  Labels
180  180      O   35               3                 6     902      14
181  181      O   30               7                 8    2764      15
182  182     AB   49               8                 5    4041      18
183  183      B   61               4                 7    1252      12
184  184      A   31               5                 6    2065      14
185  185      A   38               8                 5    4041      18
186  186      A   22               5                 5    2297      17
187  187      O   23               3                 8     662       4
188  188      O   48               8                 6    3809      18
189  189      O   34               4                 6    1484      14
190  190     AB   33               6                 8    2182      11
191  191      B   43               7                 5    3460      18
192  192      A   43               3                 6     902      14
193  193      A   36               4                 5    1716      17
194  194      A   34               4                 5    1716      17
195  195      O   56               5                 7    1833      14
196  196      O   18               3                 4    1366      17
197  197      O   51               8                 6    3809      18
198  198     AB   34               3                 6     902      14
199  199      B   50               4                 3    2179      18

In [9]:
sal_list=[]

sal=[]
from sklearn import linear_model
reg=linear_model.LinearRegression()
#Applying Regression over the clusters
for i in range(0,20):
    j=test_df.iloc[i,6]    
    cluster=train_df[train_df.Labels==j]
    reg.fit(cluster[['age','healthy_eating','active_lifestyle']],cluster.salary)
    sal_list = reg.predict(test_df[i:i+1][['age','healthy_eating','active_lifestyle']])
    
    sal.append(sal_list[0])
    

In [10]:
test_df['pred_salary_modified']=sal

In [11]:
reg1=linear_model.LinearRegression()
reg1.fit(train_df[['age','healthy_eating','active_lifestyle']],train_df.salary)
sal_list1 = reg1.predict(test_df[['age','healthy_eating','active_lifestyle']])
test_df['pred_salary_global']  = sal_list1
test_df

id groups  age  healthy_eating  active_lifestyle  salary  Labels  \
180  180      O   35               3                 6     902      14   
181  181      O   30               7                 8    2764      15   
182  182     AB   49               8                 5    4041      18   
183  183      B   61               4                 7    1252      12   
184  184      A   31               5                 6    2065      14   
185  185      A   38               8                 5    4041      18   
186  186      A   22               5                 5    2297      17   
187  187      O   23               3                 8     662       4   
188  188      O   48               8                 6    3809      18   
189  189      O   34               4                 6    1484      14   
190  190     AB   33               6                 8    2182      11   
191  191      B   43               7                 5    3460      18   
192  192      A   43               3                 6     902      14   
193  193      A   36               4                 5    1716      17   
194  194      A   34               4                 5    1716      17   
195  195      O   56               5                 7    1833      14   
196  196      O   18               3                 4    1366      17   
197  197      O   51               8                 6    3809      18   
198  198     AB   34               3                 6     902      14   
199  199      B   50               4                 3    2179      18   

     pred_salary_modified  pred_salary_global  
180            902.000000         1233.355444  
181           2764.000000         2749.598910  
182           4040.424242         3809.302088  
183           1252.000000         1541.844139  
184           2066.000000         2179.501931  
185           4038.590909         3799.572191  
186           2296.000000         2360.892665  
187           1089.402060          844.037893  
188           3807.386364         3619.065993  
189           1484.000000         1707.313224  
190           2182.000000         2277.410202  
191           3456.045455         3329.152555  
192            902.000000         1240.431732  
193           1715.000000         1898.433854  
194           1715.000000         1896.664782  
195           1834.000000         2012.263775  
196           1366.000000         1597.021447  
197           3807.886364         3621.719601  
198            902.000000         1232.470908  
199           2172.818182         2289.520477

In [12]:
salary_original=list(test_df['salary'])
salary_predicted_modified=list(test_df['pred_salary_modified'])
salary_predicted_global = list(test_df['pred_salary_global'])


In [13]:
import numpy as np
from sklearn.metrics import mean_squared_error
rms_modified=(mean_squared_error(salary_original,salary_predicted_modified))**.5
rms_global = (mean_squared_error(salary_original,salary_predicted_global))**.5
nrms_modified=rms_modified/np.std(np.array(salary_original))
nrms_global = rms_global/np.std(np.array(salary_original))
print("NRMS for Modified Clustering = ",nrms_modified)
print("NRMS for Global regression = ",nrms_global)

NRMS for Modified Clustering =  0.08725715998587306
NRMS for Global regression =  0.19266760717104733


In [14]:
from sklearn.preprocessing import PolynomialFeatures
reg2=linear_model.LinearRegression()

poly=PolynomialFeatures(degree=4)
x_poly=poly.fit_transform(train_df[['age','healthy_eating','active_lifestyle']])
reg2.fit(x_poly,train_df.salary)

sal_list1 = reg2.predict(poly.fit_transform(test_df[['age','healthy_eating','active_lifestyle']]))

test_df['pred_salary_global_poly']  = sal_list1
test_df
    

id groups  age  healthy_eating  active_lifestyle  salary  Labels  \
180  180      O   35               3                 6     902      14   
181  181      O   30               7                 8    2764      15   
182  182     AB   49               8                 5    4041      18   
183  183      B   61               4                 7    1252      12   
184  184      A   31               5                 6    2065      14   
185  185      A   38               8                 5    4041      18   
186  186      A   22               5                 5    2297      17   
187  187      O   23               3                 8     662       4   
188  188      O   48               8                 6    3809      18   
189  189      O   34               4                 6    1484      14   
190  190     AB   33               6                 8    2182      11   
191  191      B   43               7                 5    3460      18   
192  192      A   43               3                 6     902      14   
193  193      A   36               4                 5    1716      17   
194  194      A   34               4                 5    1716      17   
195  195      O   56               5                 7    1833      14   
196  196      O   18               3                 4    1366      17   
197  197      O   51               8                 6    3809      18   
198  198     AB   34               3                 6     902      14   
199  199      B   50               4                 3    2179      18   

     pred_salary_modified  pred_salary_global  pred_salary_global_poly  
180            902.000000         1233.355444               970.219005  
181           2764.000000         2749.598910              2753.634621  
182           4040.424242         3809.302088              4041.139663  
183           1252.000000         1541.844139              1180.740593  
184           2066.000000         2179.501931              2007.154777  
185           4038.590909         3799.572191              4021.335891  
186           2296.000000         2360.892665              2235.086999  
187           1089.402060          844.037893              1033.306334  
188           3807.386364         3619.065993              3878.067481  
189           1484.000000         1707.313224              1422.030386  
190           2182.000000         2277.410202              2159.980073  
191           3456.045455         3329.152555              3481.486051  
192            902.000000         1240.431732               964.585318  
193           1715.000000         1898.433854              1651.903222  
194           1715.000000         1896.664782              1650.418281  
195           1834.000000         2012.263775              1773.930019  
196           1366.000000         1597.021447              1323.632702  
197           3807.886364         3621.719601              3892.115264  
198            902.000000         1232.470908               973.464050  
199           2172.818182         2289.520477              2218.103851

In [15]:
sal_list=[]

sal=[]
reg3=linear_model.LinearRegression()
poly1=PolynomialFeatures(degree=4)

for i in range(0,20):
    j=test_df.iloc[i,6]    
    cluster=train_df[train_df.Labels==j]
    x_poly=poly1.fit_transform(cluster[['age','healthy_eating','active_lifestyle']])
    reg3.fit(x_poly,cluster.salary)
    sal_list = reg3.predict(poly1.fit_transform(test_df[i:i+1][['age','healthy_eating','active_lifestyle']]))
    
    sal.append(sal_list[0])
test_df['pred_salary_modified_poly']=sal
test_df

id groups  age  healthy_eating  active_lifestyle  salary  Labels  \
180  180      O   35               3                 6     902      14   
181  181      O   30               7                 8    2764      15   
182  182     AB   49               8                 5    4041      18   
183  183      B   61               4                 7    1252      12   
184  184      A   31               5                 6    2065      14   
185  185      A   38               8                 5    4041      18   
186  186      A   22               5                 5    2297      17   
187  187      O   23               3                 8     662       4   
188  188      O   48               8                 6    3809      18   
189  189      O   34               4                 6    1484      14   
190  190     AB   33               6                 8    2182      11   
191  191      B   43               7                 5    3460      18   
192  192      A   43               3                 6     902      14   
193  193      A   36               4                 5    1716      17   
194  194      A   34               4                 5    1716      17   
195  195      O   56               5                 7    1833      14   
196  196      O   18               3                 4    1366      17   
197  197      O   51               8                 6    3809      18   
198  198     AB   34               3                 6     902      14   
199  199      B   50               4                 3    2179      18   

     pred_salary_modified  pred_salary_global  pred_salary_global_poly  \
180            902.000000         1233.355444               970.219005   
181           2764.000000         2749.598910              2753.634621   
182           4040.424242         3809.302088              4041.139663   
183           1252.000000         1541.844139              1180.740593   
184           2066.000000         2179.501931              2007.154777   
185           4038.590909         3799.572191              4021.335891   
186           2296.000000         2360.892665              2235.086999   
187           1089.402060          844.037893              1033.306334   
188           3807.386364         3619.065993              3878.067481   
189           1484.000000         1707.313224              1422.030386   
190           2182.000000         2277.410202              2159.980073   
191           3456.045455         3329.152555              3481.486051   
192            902.000000         1240.431732               964.585318   
193           1715.000000         1898.433854              1651.903222   
194           1715.000000         1896.664782              1650.418281   
195           1834.000000         2012.263775              1773.930019   
196           1366.000000         1597.021447              1323.632702   
197           3807.886364         3621.719601              3892.115264   
198            902.000000         1232.470908               973.464050   
199           2172.818182         2289.520477              2218.103851   

     pred_salary_modified_poly  
180                 900.802214  
181                3069.065678  
182                3561.902231  
183                1679.030993  
184                2663.637808  
185                4448.547792  
186                1810.941688  
187                 628.632923  
188                3413.315178  
189                1492.163971  
190                2210.532213  
191                3566.828833  
192                 903.399654  
193                5582.890967  
194                4280.401388  
195                2523.320216  
196                1228.389756  
197                3053.408644  
198                 902.000000  
199                3235.921484

In [19]:
test_df.to_excel(r'D:\Notebooks\Salary_Prediction\Salary_prediction\Test_Result.xlsx',index=None,header=True)
train_df.to_excel(r'D:\Notebooks\Salary_Prediction\Salary_prediction\Train_Result.xlsx',index=None,header=True)
